### ISSUE TITLE
telegram-purple is abandoned

### ISSUE THREAD

**Issue by pbtrung** [mbologna/docker-bitlbee#10]
Please use [tdlib-purple](https://github.com/ars3niy/tdlib-purple/) instead.

**Comment by mbologna** [comment]
Hey @pbtrung !
Thanks for the issue, I have updated the container with the updated Telegram library you suggested:

https://github.com/mbologna/docker-bitlbee/commit/899ef9199632c1a568542bec4a01a418c16f5195
