### ISSUE TITLE
Plugins Telegram not installed in docker image

### ISSUE THREAD

**Issue by raymand211092** [mbologna/docker-bitlbee#13]
I used docker image https://hub.docker.com/r/mbologna/docker-bitlbee
![imagen](https://github.com/mbologna/docker-bitlbee/assets/50679989/c1edd824-8a0a-400c-a0d7-0e1d2f479c43)

**Comment by mbologna** [comment]
Thanks for your report. I can confirm, Telegram plugin is not enabled.
I am gonna release a new version that fixes the problem.
