### ISSUE TITLE
SSL routines::wrong version 

### ISSUE THREAD

**Issue by miztizm** [mbologna/docker-bitlbee#14]
Hello, I'm struggling to bypass this error. I've tried every configuration, but the connection on the secure port from mIRC doesn't work.
```
bitlbee-stunnel  | 2024.02.27 16:38:32 LOG6[0]: Peer certificate not required
bitlbee-stunnel  | 2024.02.27 16:38:32 LOG7[0]: TLS state (accept): before SSL initialization
bitlbee-stunnel  | 2024.02.27 16:38:33 LOG3[0]: SSL_accept: ssl/record/ssl3_record.c:354: error:0A00010B:SSL routines::wrong version number
bitlbee-stunnel  | 2024.02.27 16:38:33 LOG5[0]: Connection reset: 0 byte(s) sent to TLS, 0 byte(s) sent to socket
bitlbee-stunnel  | 2024.02.27 16:38:33 LOG7[0]: local_rfd/local_wfd reset (FD=3)
bitlbee-stunnel  | 2024.02.27 16:38:33 LOG7[0]: Local descriptor (FD=3) closed
bitlbee-stunnel  | 2024.02.27 16:38:33 LOG7[0]: Service [bitlbee-stunnel] finished (0 left)
bitlbee-stunnel  | 2024.02.27 16:39:02 LOG7[ui]: Found 1 ready file descriptor(s)

```

**Comment by mbologna** [comment]
> Hello, I'm struggling to bypass this error. I've tried every configuration, but the connection on the secure port from mIRC doesn't work.
> 
> ```
> bitlbee-stunnel  | 2024.02.27 16:38:32 LOG6[0]: Peer certificate not required
> bitlbee-stunnel  | 2024.02.27 16:38:32 LOG7[0]: TLS state (accept): before SSL initialization
> bitlbee-stunnel  | 2024.02.27 16:38:33 LOG3[0]: SSL_accept: ssl/record/ssl3_record.c:354: error:0A00010B:SSL routines::wrong version number
> bitlbee-stunnel  | 2024.02.27 16:38:33 LOG5[0]: Connection reset: 0 byte(s) sent to TLS, 0 byte(s) sent to socket
> bitlbee-stunnel  | 2024.02.27 16:38:33 LOG7[0]: local_rfd/local_wfd reset (FD=3)
> bitlbee-stunnel  | 2024.02.27 16:38:33 LOG7[0]: Local descriptor (FD=3) closed
> bitlbee-stunnel  | 2024.02.27 16:38:33 LOG7[0]: Service [bitlbee-stunnel] finished (0 left)
> bitlbee-stunnel  | 2024.02.27 16:39:02 LOG7[ui]: Found 1 ready file descriptor(s)
> ```

How did you launch `bitlbee` and `stunnel-bitlbee`? Have you tried with another client that is not mIRC?

I have just set up an instance using `docker-compose` and the supplied `docker-compose.yml` file and I can connect to the instance using TLS and irssi with no problem.

**Comment by mbologna** [comment]
No answer, closing.

**Comment by miztizm** [comment]
In MIRC, for those wondering, you need to use a plus sign with the stunnel port number. Therefore, the port will be +16697.
