### ISSUE TITLE
Mattermost support

### ISSUE THREAD

**Issue by fuzzy76** [mbologna/docker-bitlbee#4]
Since more and more run Mattermost instead of Slack in order to have better control of internal communication, adding the [libpurple mattermost plugin](https://github.com/EionRobb/purple-mattermost) would be a great addition to this image.

**Comment by mbologna** [comment]
Thanks for the suggestion!
Mattermost plug-in has been included, the image has been re-built and pushed to DockerHub.
Enjoy
